//Autogenerated class by script: Assets/Scripts/EditorTools/Editor/OpenSceneReloadMenu.cs
using UnityEngine;
using UnityEditor;

public static class OpenSceneMenu {

	[MenuItem("Open scene/2DTopDownExample", false, 0)]
	static void Open2DTopDownExample() {
		OpenScene("Assets/_Scenes/2DTopDownExample.unity");
	}

	[MenuItem("Open scene/LandmassGenerationExample", false, 0)]
	static void OpenLandmassGenerationExample() {
		OpenScene("Assets/_Scenes/LandmassGenerationExample.unity");
	}

	[MenuItem("Open scene/PlatformControllerExample", false, 0)]
	static void OpenPlatformControllerExample() {
		OpenScene("Assets/_Scenes/PlatformControllerExample.unity");
	}

	static void OpenScene(string scenePath) {
	if (UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) {
			UnityEditor.SceneManagement.EditorSceneManager.OpenScene(scenePath);
		}
	}
}
